name: Create tag, build and release package.

on:
  push:
    branches:
      - main
     
# default: least privileged permissions across all jobs
permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write

    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name>

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          patchList: 'fix, bugfix, perf, refactor, test, tests, chore, docs'

      - name: 'Update TOML file'
        run: |
          OLD_VERSION=$(grep ^version pyproject.toml | cut -d '"' -f 2)
          OLD_VERSION="\"$OLD_VERSION\""
          NEW_VERSION="\"${{ steps.semver.outputs.next }}\""
          sed -i "s+version = $OLD_VERSION+version = $NEW_VERSION+g" pyproject.toml

      - name: 'Update CHANGELOG.md'
        uses: orhun/git-cliff-action@v4
        with:
          args: --unreleased --tag ${{ steps.semver.outputs.next }} --prepend CHANGELOG.md
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: 'Commit and push new version file'
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -a -m "Update version number to ${{ steps.semver.outputs.next }}"
          git tag ${{ steps.semver.outputs.next }}
          git push origin tag ${{ steps.semver.outputs.next }}
          git push origin main

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.semver.outputs.next }}
          release_name: Release ${{ steps.semver.outputs.next }}
          draft: false
          prerelease: false

      # Publish to PyPI
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
      - name: Build package
        run: python -m build
      - name: Save built package
        uses: actions/upload-artifact@v6
        with:
          name: package
          path: dist
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true